const actionTypes = {
    GET_HOME_START: 'GET_HOME_START',
    GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
    GET_HOME_FAIL: 'GET_HOME_FAIL',

    SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
    SET_CUR_PLAYLIST_ID: "SET_CUR_PLAYLIST_ID",
    SET_CUR_SONG_INFO: "SET_CUR_SONG_INFO",
    LOADING: 'LOADING',
    SCROLL: 'SCROLL',
    PLAY: "PLAY",
    PLAYLIST: "PLAYLIST",
    SET_ALBUM: "SET_ALBUM",
    SET_RECENT_SONG: "SET_RECENT_SONG",
    SEARCH: "SEARCH",
}



export default actionTypes;